"""The reference scenarios, asserted.

Two layers, and both are needed.

**Pins.** The headline outputs of each reference scenario, written down. They change when the
model, a measured constant or the DSL core changes, and every one of those is a decision somebody
should make deliberately — so a diff that moves them is a diff that has to say why. This is the
sixth of the toolkit's outputs, and it is the one that makes the other five safe to rely on.

**Invariants.** Things that must hold whatever the numbers are: the accounting adds up, a node
count is a whole number, a ceiling's allowed level is below its limit. A pin catches a change; an
invariant catches a class of nonsense, including in a model somebody adds tomorrow.
"""

from __future__ import annotations

import math

import pytest

from bench.stamp import load_result
from sizing.dsl import Ceiling, discover, load_scenario, scenarios_for
from sizing.evaluate import check_units, evaluate, point

#: point, p5, p95 for every output of each reference scenario. Generated by the build, checked
#: here. Moving one is fine; moving one without noticing is not.
PINS = {
    "storage_cluster-reference": {
        "nodes_recommended": (121.0, 46.0, 379.0),
        "nodes_purchased": (121.0, None, None),
        "tco": (4150035.563025671, 3207410.984364548, 5732007.061221861),
        "cost_per_usable_tb_month": (6.526718041245973, 2.3666590199721127, 15.873613970274938),
        "capex": (2025596.326127275, 1475271.711030295, 2859544.4053405644),
        "annual_opex": (424887.8473796792, 318062.2801872229, 611521.5543813157),
        "fill_level": (0.7462631549076367, 0.23751424273852662, 2.3483313911156083),
        "read_utilisation": (0.5458080607924731, 0.26650505006771763, 1.0242176962099736),
    },
    "web_service-reference": {
        "hosts_recommended": (54.0, 20.0, 230.0),
        "hosts": (54.0, None, None),
        "tco": (2002083.1707651545, 1508229.8444723955, 2923723.9593550325),
        "cost_per_million_requests": (1.8207372530067034, 0.5523457592287855, 5.982886615297304),
        "cost_per_stored_tb_month": (839.6414698789445, 305.33281615953297, 2107.817738138934),
        "capex": (421214.32422070147, 272129.78204760165, 658773.216029522),
        "annual_opex": (316173.76930889057, 227660.27329566484, 484257.1276373279),
        "queueing_headroom": (0.643907479030284, 0.15608313209178654, 2.4846275656339345),
        "failure_headroom": (0.6560566767478365, 0.15902809684823532, 2.531507331023254),
        "cache_fill": (0.7457807356330546, 0.19351967005914503, 2.6720696883949917),
        "disk_fill": (0.6699972825041127, 0.21319715097561925, 2.1199789434396727),
        "scaling_loss": (0.3210474303939056, 0.21251187466674934, 0.4565840519300162),
        "coordination_headroom": (0.9483835953428347, 0.23256931780969597, 3.8088382686495614),
        "utilisation": (0.643907479030284, 0.15608313209178654, 2.4846275656339345),
        "residence_time": (0.03670898993926409, 0.012809150925497385, 0.856577120132588),
        "waiting_time": (0.0236371931695396, 0.0020883616834668677, 0.8394455777299362),
        "concurrency": (1562.3357108628495, 159.79752424384506, 107335.91083538589),
        "in_flight_unqueued": (556.3360618821654, 134.85582612730357, 2146.7182167077194),
        "optimism": (1.4728569339978588, 1.2698604179930921, 1.8402109904135502),
        "headroom_to_peak": (0.32846489726073863, 0.18552259764577544, 0.5839492207928927),
    },
    "service_tier-reference": {
        "utilisation": (0.5878614710768895, 0.23168842385794025, 1.3186737705994391),
        "utilisation_including_coordination": (
            0.8939900075324693,
            0.41339567207336353,
            1.835670425069286,
        ),
        "optimism": (1.5207494478159798, 0.9635533676255424, 2.5630744060972415),
        "residence_time": (0.01653982675471082, 0.006704620123792237, 0.47161539351445725),
        "waiting_time": (0.009723126887381197, 0.0015958441132010212, 0.4621830856441681),
        "concurrency": (91.28759266266023, 19.299538869779, 4219.756065918202),
        "busy_nodes": (37.623134148920926, 14.828059126908176, 84.3951213183641),
        "achievable_throughput": (6173.737128031247, 4207.890485276353, 8384.711137091275),
        "scaling_efficiency": (0.6308261122478787, 0.48729853333873535, 0.7487756138413769),
        "peak_nodes": (164.40112916277405, 92.48190967899484, 291.04849255061293),
        "headroom_to_peak": (0.38929173008680135, 0.21989462800516746, 0.6920272324544551),
        "queueing_headroom": (0.5878614710768895, 0.23168842385794025, 1.3186737705994391),
        "scaling_loss": (0.36917388775212134, 0.251224386158623, 0.5127014666612645),
        "coordination_headroom": (0.8939900075324693, 0.41339567207336353, 1.835670425069286),
    },
    "observability-reference": {
        "metrics_ingest": (4.691199947653698, 0.7087674746854326, 29.10375682615168),
        "logs_ingest": (44.67582461292441, 9.662904248123636, 164.16836699415467),
        "known_ingest": (49.36702456057811, 12.455331200106434, 182.09640536115296),
        "known_stored": (277.9276075876119, 74.61499109864353, 1301.0762787876827),
        "active_series": (15019917.210191535, 2269388.9349276964, 93180409.27366705),
        "label_cardinality": (76.31587707750207, 17.926983727788215, 300.4866647992642),
        "known_storage_cost": (4084.6849441327413, 957.4699566381062, 21788.208342526315),
        "store_fill": (0.579015849140858, 0.155447898122174, 2.710575580807672),
        "quoted_pipeline_utilisation": (0.5142398391726887, 0.129743033334442, 1.8968375558453434),
        "query_utilisation": (0.5686076313785159, 0.05914481544577415, 3.3746456809609255),
    },
}

#: Units that count things somebody buys or provisions.
COUNT_UNITS = ("node", "drive", "core", "host")

MODELS = {model.name: model for model in discover()}


def _scenario(model, name):
    for scenario in scenarios_for(model):
        if scenario.name == name:
            return scenario
    raise AssertionError(f"{model.name} has no scenario {name!r}")


@pytest.mark.parametrize("result_name", sorted(PINS))
def test_the_reference_outputs_are_what_the_book_publishes(result_name):
    model_name, scenario_name = result_name.rsplit("-", 1)
    model = MODELS[model_name]
    evaluation = evaluate(model, _scenario(model, scenario_name))
    for output, (at_point, p5, p95) in PINS[result_name].items():
        assert evaluation.point[output] == pytest.approx(at_point, rel=1e-9), (
            f"{result_name}: {output} at the point estimate moved. If that was deliberate, "
            "re-run `python3 -m bench.run_models` and update the pin in the same commit."
        )
        if p5 is None:
            assert output not in evaluation.summaries
            continue
        assert evaluation.summaries[output]["p5"] == pytest.approx(p5, rel=1e-9)
        assert evaluation.summaries[output]["p95"] == pytest.approx(p95, rel=1e-9)


@pytest.mark.parametrize("result_name", sorted(PINS))
def test_the_stamped_result_agrees_with_a_fresh_run(result_name):
    """The committed file and the code that claims to produce it have not drifted apart."""
    stamped = load_result(result_name)["summary"]
    model_name, scenario_name = result_name.rsplit("-", 1)
    model = MODELS[model_name]
    fresh = evaluate(model, _scenario(model, scenario_name))
    for output in stamped["outputs"]:
        node = stamped["nodes"][output]
        if node.get("blocked_by"):
            assert output not in fresh.point, f"{output} is stamped as blocked but now evaluates"
            continue
        assert fresh.point[output] == pytest.approx(node["point"], rel=1e-9), (
            f"{result_name}: {output} differs from the stamped result. Re-run "
            "`python3 -m bench.run_models`."
        )


@pytest.mark.parametrize("model_name", sorted(MODELS))
def test_every_model_typechecks(model_name):
    problems, _ = check_units(MODELS[model_name])
    assert not problems, "\n".join(problems)


@pytest.mark.parametrize("model_name", sorted(MODELS))
def test_every_scenario_evaluates(model_name):
    model = MODELS[model_name]
    for scenario in scenarios_for(model):
        evaluate(model, scenario)


@pytest.mark.parametrize("model_name", sorted(MODELS))
def test_a_decision_about_countable_things_is_a_whole_number(model_name):
    """You cannot decide to buy two thirds of a machine.

    Only *decisions* though, and the distinction is worth stating because the first version of
    this test did not make it and failed on a model that was right. A node whose unit is `node`
    is a quantity of machines, and there are perfectly good fractional ones: the average number
    busy at any moment, the point at which a scaling curve turns over. Neither is something
    anybody buys. An input with a count unit is something somebody chose, and 64.3 of them is not
    a choice that can be made.
    """
    model = MODELS[model_name]
    values = point(model, _scenario(model, "reference"))
    for name, node in model.nodes.items():
        if node.kind != "input" or node.unit not in COUNT_UNITS or name not in values:
            continue
        assert values[name] == math.floor(values[name]), (
            f"{model_name}: {name} is {values[name]}, and it is a decision counted in "
            f"{node.unit}s. Somebody has to be able to act on it."
        )


@pytest.mark.parametrize("model_name", sorted(MODELS))
def test_a_sizing_chain_rounds_up_rather_than_to_nearest(model_name):
    """Where a chain lands between two machines, it must land on the larger.

    Rounding to nearest saves half a machine and loses the thing the chain was computing. Every
    derived node in this book that turns a demand into a count of machines says `ceil`, and this
    checks that what comes out of them is whole — so a chain that acquires a division after the
    rounding, which is the way this goes wrong, fails here.
    """
    model = MODELS[model_name]
    values = point(model, _scenario(model, "reference"))
    rounded = [
        name
        for name, node in model.nodes.items()
        if node.kind == "derived" and node.formula_text.strip().startswith("ceil(")
    ]
    for name in rounded:
        assert values[name] == math.floor(values[name]), (
            f"{model_name}: {name} rounds up and is still {values[name]}. Something divides it "
            "after the rounding, which throws the rounding away."
        )


@pytest.mark.parametrize("model_name", sorted(MODELS))
def test_every_ceiling_leaves_room_below_its_limit(model_name):
    model = MODELS[model_name]
    evaluation = evaluate(model, _scenario(model, "reference"))
    for name, report in evaluation.ceilings.items():
        assert isinstance(model.nodes[name], Ceiling)
        assert 0.0 <= report["headroom"] < 1.0, (
            f"{model_name}: {name} declares a headroom of {report['headroom']}, which is either "
            "negative or leaves nothing at all"
        )
        assert report["allowed"] < report["limit"] or report["headroom"] == 0.0
        assert 0.0 <= report["p_over_allowed"] <= 1.0


def test_the_storage_model_accounting_adds_up():
    """The one arithmetic identity worth asserting directly: a total is its parts."""
    model = MODELS["storage_cluster"]
    values = point(model, _scenario(model, "reference"))
    assert values["capex"] == pytest.approx(
        values["drive_capex"] + values["chassis_capex"] + values["network_capex"]
    )
    assert values["tco"] == pytest.approx(values["capex"] + values["lifecycle_opex"])
    assert values["tco"] > values["capex"], "a five-year total that is not above its capital cost"


def test_the_observability_traces_chain_is_blocked_and_says_why():
    """The unmeasured constant propagates, and the reason survives into the stamped result."""
    model = MODELS["observability"]
    blocked = model.blocked()
    assert "spans_per_request" in model.unmeasured
    assert "traces_ingest" in blocked, "the traces chain should be unevaluable"
    assert "spans_per_request" in blocked["traces_ingest"], (
        "a blocked node has to name which missing constant blocked it, or the box on the page "
        "cannot tell the reader what to go and measure"
    )
    assert "metrics_ingest" not in blocked, (
        "only the chain downstream of the missing constant is blocked; the others still compute"
    )


def test_a_scenario_cannot_pin_a_derived_node():
    """Overriding a derived node would make the graph and the number disagree."""
    model = MODELS["storage_cluster"]
    for scenario in scenarios_for(model):
        for name in scenario.overrides:
            assert model.nodes[name].kind != "derived", (
                f"scenario {scenario.name!r} pins {name!r}, which is computed from other nodes"
            )


def test_scenario_files_load_from_disk():
    for model in MODELS.values():
        assert model.path is not None
        for path in sorted((model.path.parent / "scenarios").glob("*.yaml")):
            assert load_scenario(path).samples > 0


# -- what a measurement would buy ------------------------------------------------------------


def test_pinning_every_uncertain_input_leaves_no_interval():
    """The premise ch19's value-of-information table rests on.

    A model whose inputs are all known is arithmetic, and arithmetic has no interval. If this
    ever stops being true, something is generating randomness that is not a declared input, and
    every figure in the book that calls itself a 90% interval is about something else.
    """
    from bench.run_information import without_uncertainty
    from sizing.evaluate import sampled_inputs

    model = MODELS["storage_cluster"]
    scenario = _scenario(model, "reference")
    pinned = without_uncertainty(model, scenario, tuple(sampled_inputs(model)))
    assert evaluate(pinned, scenario).samples == {}, (
        "an input kept its uncertainty after being pinned, or something else is drawing numbers"
    )


def test_knowing_one_input_never_widens_the_interval():
    """Removing uncertainty cannot add any, and the bound has to be a bound.

    Sampling noise means the two runs are not exactly ordered, so this allows the noise ch14
    measures and nothing beyond it.
    """
    from bench.run_information import without_uncertainty
    from sizing import mc
    from sizing.evaluate import sampled_inputs

    model = MODELS["storage_cluster"]
    scenario = _scenario(model, "reference")
    baseline = mc.half_width(evaluate(model, scenario).samples["tco"])
    for name in sampled_inputs(model):
        if name not in model.ancestors("tco"):
            continue
        thinner = without_uncertainty(model, scenario, (name,))
        assert mc.half_width(evaluate(thinner, scenario).samples["tco"]) <= baseline * 1.01, (
            f"knowing {name!r} exactly widened the interval, which is not a thing that can happen"
        )


def test_a_three_way_max_leaves_its_third_argument_alone(tmp_path):
    """`np.maximum(a, b, c)` writes into c. The evaluator must not.

    Found by the web service model, whose recommended host count is the largest of three chains:
    the storage chain reported binding in every sample, because its samples had been overwritten
    with the maximum. No model had put three arguments into `max` before.
    """
    import numpy as np

    from sizing.dsl import load_model, load_scenario

    (tmp_path / "scenarios").mkdir()
    (tmp_path / "model.yaml").write_text(
        """
model: three_way
title: three uncertain inputs and the largest of them
currency: USD
nodes:
  a: {kind: input, unit: host, distribution: {uniform: {minimum: 1, maximum: 10}},
      provenance: {kind: assumption, source: "uniform, for the test"}}
  b: {kind: input, unit: host, distribution: {uniform: {minimum: 1, maximum: 10}},
      provenance: {kind: assumption, source: "uniform, for the test"}}
  c: {kind: input, unit: host, distribution: {uniform: {minimum: 1, maximum: 10}},
      provenance: {kind: assumption, source: "uniform, for the test"}}
  largest: {kind: derived, unit: host, formula: "max(a, b, c)"}
  smallest: {kind: derived, unit: host, formula: "min(a, b, c)"}
outputs: [largest, smallest]
"""
    )
    (tmp_path / "scenarios" / "reference.yaml").write_text(
        "scenario: reference\ntitle: r\nsamples: 2000\nseed: 7\noverrides: {}\n"
    )
    model = load_model(tmp_path / "model.yaml")
    scenario = load_scenario(tmp_path / "scenarios" / "reference.yaml")
    once = evaluate(model, scenario).samples
    again = evaluate(model, scenario).samples
    for name in ("a", "b", "c"):
        assert np.array_equal(once[name], again[name]), f"{name}'s samples were written to"
    assert np.array_equal(once["largest"], np.maximum.reduce([once["a"], once["b"], once["c"]]))
    assert np.array_equal(once["smallest"], np.minimum.reduce([once["a"], once["b"], once["c"]]))
    assert not np.array_equal(once["c"], once["largest"]), "c is not the maximum in every sample"
