"""The storage model as the book builds it, one chapter at a time.

The book does not hand a reader a finished model and explain it backwards. It starts with what
arrives and what accumulates, and adds nodes as the chapters earn them. Those intermediate models
are real: they load, they typecheck, they classify, and `make check` runs the same rules over them
that it runs over the finished file.

They are **derived** from ``models/storage_cluster/model.yaml`` rather than kept beside it. A
second copy of a model is a copy that drifts, and a book describing a model the repository no
longer has is the failure this whole repository exists to prevent. ``stages.yaml`` says which
chapter introduces which node, and everything else is computed.

One node is not simply added. ``annual_growth`` is a single number until ch04 gives it a shape, so
a stage before that declares it with ``certain_for_now`` — a value and a provenance that says the
distribution is coming. That is the only kind of edit a stage may make to a node, because any
other would let the staged model say something the real one does not.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass
from pathlib import Path

import yaml

from sizing.dsl import MODELS_DIR

MODEL_PATH = MODELS_DIR / "storage_cluster" / "model.yaml"
STAGES_PATH = MODELS_DIR / "storage_cluster" / "stages.yaml"

#: Where the built stages land. Gitignored, like every other build product.
OUT_DIR = MODELS_DIR / "_out" / "stages"


@dataclass(frozen=True)
class Stage:
    """One chapter's worth of model."""

    index: int
    stage: str
    chapter: str
    title: str
    classification: str
    outputs: tuple[str, ...]
    introduces: tuple[str, ...]
    certain_for_now: dict[str, dict]

    @property
    def name(self) -> str:
        return f"storage_cluster_{self.stage}"

    @property
    def path(self) -> Path:
        return OUT_DIR / f"{self.index:02d}-{self.stage}" / "model.yaml"


def _raw_model() -> dict:
    return yaml.safe_load(MODEL_PATH.read_text())


def stages() -> tuple[Stage, ...]:
    """The manifest, in reading order."""
    spec = yaml.safe_load(STAGES_PATH.read_text())
    return tuple(
        Stage(
            index=i + 1,
            stage=one["stage"],
            chapter=one["chapter"],
            title=one["title"],
            classification=one["classification"],
            outputs=tuple(one["outputs"]),
            introduces=tuple(one.get("introduces") or ()),
            certain_for_now=one.get("certain_for_now") or {},
        )
        for i, one in enumerate(spec["stages"])
    )


def nodes_by(index: int) -> tuple[str, ...]:
    """Every node the book has introduced by the end of stage ``index``, in the model's order."""
    introduced = {n for s in stages() if s.index <= index for n in s.introduces}
    return tuple(n for n in _raw_model()["nodes"] if n in introduced)


def build(stage: Stage) -> dict:
    """The stage as a model document, ready to be written out and loaded like any other."""
    raw = _raw_model()
    keep = nodes_by(stage.index)

    nodes = {}
    for name in keep:
        spec = copy.deepcopy(raw["nodes"][name])
        pending = stage.certain_for_now.get(name)
        if pending is not None:
            # The one permitted edit: a node that is not uncertain yet.
            spec.pop("distribution", None)
            spec["value"] = pending["value"]
            spec["provenance"] = {"kind": "assumption", "source": pending["source"]}
        nodes[name] = spec

    return {
        "model": stage.name,
        "title": f"{raw['title']} — {stage.title}",
        "currency": raw["currency"],
        "description": (
            f"The storage model as it stands at the end of {stage.chapter}, built by "
            f"bench/stages.py from models/storage_cluster/model.yaml. Not a model anybody would "
            f"ship: it is the finished model with everything the book has not introduced yet "
            f"removed, so that a reader can see what it looked like when it had "
            f"{len(keep)} nodes in it."
        ),
        "nodes": nodes,
        "outputs": list(stage.outputs),
        # Correlations name inputs, and an input the stage has not introduced is not there to
        # correlate. The pairs the finished model declares are ch14's subject anyway.
        "correlations": [
            c for c in raw.get("correlations", []) if c["a"] in nodes and c["b"] in nodes
        ],
    }


def write_all() -> tuple[Path, ...]:
    """Write every stage, and return where they landed."""
    written = []
    for stage in stages():
        stage.path.parent.mkdir(parents=True, exist_ok=True)
        stage.path.write_text(
            "# Generated by bench/stages.py from models/storage_cluster/model.yaml.\n"
            "# Do not edit: say which chapter introduces the node in stages.yaml instead.\n"
            + yaml.safe_dump(build(stage), sort_keys=False, width=98, allow_unicode=True)
        )
        written.append(stage.path)
    return tuple(written)


if __name__ == "__main__":  # pragma: no cover - a convenience, not a runner
    for path in write_all():
        print(f"  wrote {path.relative_to(MODELS_DIR.parent)}")
