#!/usr/bin/env python3
"""Make the built site work offline: a service worker, and the line in each page that installs it.

    python3 scripts/build-offline.py --inject _build/html --base /sizing-and-tco/

The book is a set of static pages with the interactive models inlined into them, so it has
nothing a server has to do -- but a browser only knows to keep it if something asks. This writes
``sw.js`` at the site root with a list of every page, model viewer, playground, problem set, the
search index and the icons, and adds one line to every page's head that registers it. On the
first visit the worker fetches the whole list; after that every page opens with the network off,
and a new deploy is picked up the next time a page is opened online.

The Python runtime the playground, the viewer's Resample and a problem's Check fetch is not in
the list. Ten megabytes that most readers never press the button for is not something to make
every visitor pay; instead the worker keeps whatever the runtime and its wheels were fetched from
the first time a reader does press it, so that from then on those work offline too. A reader who
wants it ahead of need presses the offline control in every page's header, which fetches the same
files into the same cache and says when they are kept. The front matter says this in two
sentences.

The worker's version is a hash of everything it caches, so a rebuild that changes nothing keeps
the reader's copy and a rebuild that changes anything replaces it. Mirrors ``build-icons.py``:
idempotent, because the deploy may run twice and a page that registers two workers is a bug.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from sizing.playground.toolkit import PYODIDE, RUNTIME_CACHE, problem_wheels, wheels  # noqa: E402

#: What the worker keeps from the first visit. Everything a page needs is inside the page --
#: figures are inlined -- so this is the pages themselves and the things they embed or fetch:
#: a chapter's problem set is fetched the first time Check is pressed, and kept from the start
#: so that a chapter works offline whether or not it was.
PRECACHED = (
    "*.html",
    "models/*.html",
    "futures/*.html",
    "playground/*/index.html",
    "problems/*.json",
)
PRECACHED_FILES = (
    "search.json",
    "favicon.svg",
    "favicon-32.png",
    "favicon-16.png",
    "apple-touch-icon.png",
    "icon-192.png",
    "icon-512.png",
    "site.webmanifest",
)

#: Where the Python runtime and its wheels come from. Kept once fetched, never fetched ahead.
RUNTIME_HOSTS = ("cdn.jsdelivr.net", "pypi.org", "files.pythonhosted.org")

#: The line that installs the worker. Matched on to make the injection idempotent.
REGISTER = '<script>if ("serviceWorker" in navigator) addEventListener("load", () => navigator.serviceWorker.register("{base}sw.js"));</script>'
LINKED = "serviceWorker.register("

WORKER = r"""// Generated by scripts/build-offline.py. Not committed: it lists what this build produced.
const VERSION = "%(version)s";
const BASE = "%(base)s";
const SITE = "sizing-and-tco-site-" + VERSION;
const RUNTIME = "%(runtime_cache)s";
const PRECACHE = %(precache)s;
const RUNTIME_HOSTS = %(runtime_hosts)s;

// The first visit fetches every page. If one is missing the install fails loudly rather than
// leaving a reader with a book that has a hole in it, which is why the list is checked at build
// time against the files that exist.
self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(SITE)
      .then((cache) => cache.addAll(PRECACHE.map((path) => BASE + path)))
      .then(() => self.skipWaiting()));
});

// A new build replaces the old site cache and keeps the runtime: the runtime is pinned to a
// version, and a reader who fetched it once should not fetch it again because a chapter changed.
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys
        .filter((key) => key.startsWith("sizing-and-tco-site-") && key !== SITE)
        .map((key) => caches.delete(key))))
      .then(() => self.clients.claim()));
});

async function cacheFirst(request, name) {
  const cache = await caches.open(name);
  const kept = await cache.match(request);
  if (kept) return kept;
  const fresh = await fetch(request);
  if (fresh.ok) cache.put(request, fresh.clone());
  return fresh;
}

// Pages come from the network when there is one, so an update shows up as soon as it is
// deployed, and from the cache when there is not. Everything else is content-addressed by
// this build's version and can be served from the cache without asking.
async function networkFirst(request) {
  const cache = await caches.open(SITE);
  try {
    const fresh = await fetch(request);
    if (fresh.ok) cache.put(request, fresh.clone());
    return fresh;
  } catch (error) {
    const kept = await cache.match(request, { ignoreSearch: true });
    if (kept) return kept;
    throw error;
  }
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin === self.location.origin) {
    if (!url.pathname.startsWith(BASE)) return;
    const page = request.mode === "navigate" || url.pathname.endsWith(".html") || url.pathname.endsWith("/");
    event.respondWith(page ? networkFirst(request) : cacheFirst(request, SITE));
  } else if (RUNTIME_HOSTS.includes(url.hostname)) {
    event.respondWith(cacheFirst(request, RUNTIME));
  }
});
"""


def precache(tree: Path) -> list[str]:
    """Every path the worker keeps, relative to the site root, in a stable order."""
    found: set[str] = set()
    for pattern in PRECACHED:
        found |= {p.relative_to(tree).as_posix() for p in tree.glob(pattern) if p.is_file()}
    found |= {name for name in PRECACHED_FILES if (tree / name).is_file()}
    return sorted(found)


def version_of(tree: Path, paths: list[str]) -> str:
    digest = hashlib.sha256()
    for path in paths:
        digest.update(path.encode())
        digest.update((tree / path).read_bytes())
    return digest.hexdigest()[:16]


def worker(tree: Path, base: str) -> str:
    paths = precache(tree)
    return WORKER % {
        "version": version_of(tree, paths),
        "base": base,
        "precache": json.dumps(paths, indent=2),
        "runtime_hosts": json.dumps(list(RUNTIME_HOSTS)),
        "runtime_cache": RUNTIME_CACHE,
    }


def inject(html: Path, base: str) -> bool:
    """Register the worker from one built page's head. True if the file changed."""
    text = html.read_text()
    if LINKED in text or "</head>" not in text:
        return False
    html.write_text(text.replace("</head>", REGISTER.format(base=base) + "\n</head>", 1))
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inject", type=Path, required=True, metavar="DIR", help="a built site")
    parser.add_argument("--base", default="/", help="the path the site is served from")
    args = parser.parse_args()

    tree = args.inject
    if not tree.is_dir():
        print(f"build-offline: {tree} is not a directory")
        return 1
    base = args.base if args.base.endswith("/") else args.base + "/"
    for url in (PYODIDE, *wheels(), *problem_wheels()):
        if url.split("/")[2] not in RUNTIME_HOSTS:
            print(f"build-offline: {url} is not on a host the worker keeps")
            return 1

    (tree / "sw.js").write_text(worker(tree, base))
    pages = sorted(tree.rglob("*.html"))
    added = sum(inject(page, base) for page in pages)
    linked = sum(LINKED in page.read_text() for page in pages)
    kept = precache(tree)
    print(
        f"build-offline: sw.js keeps {len(kept)} file(s), {added} page(s) edited, "
        f"{linked} of {len(pages)} page(s) register it"
    )
    if pages and not linked:
        print("build-offline: no page's head was found — nothing registers the worker")
        return 1
    return 0


if __name__ == "__main__":  # pragma: no cover - a thin wrapper around main()
    raise SystemExit(main())
