#!/usr/bin/env python3
"""Render every declared figure from committed results.

    python3 scripts/render-figures.py            # write the fragments and diagrams
    python3 scripts/render-figures.py --check    # fail if a committed one is stale

Writes one markdown fragment per :class:`bench.figures.Table` into ``chapters/_generated/`` and
one SVG per :class:`bench.figures.Diagram` into ``chapters/_figures/``. Pages include those files
rather than containing numbers, so every figure in the book traces back to a stamped result.

``--check`` is what makes this worth having. It regenerates everything and *diffs* it against
what is committed, so a result that changed without its fragment being re-rendered fails CI. A
build that simply re-rendered on the way past would paper over exactly that case.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from bench.figures import FIGURES, Diagram, Table  # noqa: E402
from bench.stamp import shown  # noqa: E402
from bench.tables import conditions  # noqa: E402

FRAGMENTS = ROOT / "chapters" / "_generated"
DIAGRAMS = ROOT / "chapters" / "_figures"

BANNER = "<!-- Generated by scripts/render-figures.py. Do not edit by hand. -->"


def render_table(figure: Table) -> str:
    if figure.pending is not None:
        # No numbers, not even placeholder ones. The reader of a draft sees a missing
        # measurement; they never see an invented one.
        return "\n".join(
            [
                BANNER,
                "",
                ":::{warning} Not measured yet — this needs the reference machine",
                figure.pending,
                "",
                "Nothing is estimated in its place: this book publishes measurements or it",
                "publishes nothing.",
                ":::",
                "",
            ]
        )
    body = figure.render(figure.result, *figure.args)
    caption = conditions(figure.conditions_from or figure.result)
    return "\n".join([BANNER, "", body, "", caption, ""])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify instead of writing")
    args = parser.parse_args()

    FRAGMENTS.mkdir(parents=True, exist_ok=True)
    DIAGRAMS.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    pending = 0

    for name in sorted(FIGURES):
        figure = FIGURES[name]
        try:
            if isinstance(figure, Diagram):
                target, rendered = DIAGRAMS / f"{name}.svg", figure.render()
            else:
                target, rendered = FRAGMENTS / f"{name}.md", render_table(figure)
        except FileNotFoundError as exc:
            print(f"  MISSING RESULT for {name}: {exc}")
            stale.append(name)
            continue
        if figure.pending is not None:
            pending += 1

        if args.check:
            current = target.read_text() if target.exists() else ""
            if current != rendered:
                stale.append(name)
                print(f"  STALE: {shown(target)}")
        else:
            target.write_text(rendered)
            state = " (pending measurement)" if figure.pending else ""
            print(f"  wrote {shown(target)}{state}")

    # A renamed figure leaves its old fragment on disk, still included by whichever page referred
    # to it, and nothing regenerates it ever again. That is worse than a missing file: the page
    # goes on showing a frozen copy and the build stays green, because the include still resolves.
    expected = {
        f"{name}.svg" if isinstance(FIGURES[name], Diagram) else f"{name}.md" for name in FIGURES
    }
    orphans = sorted(
        path
        for directory in (FRAGMENTS, DIAGRAMS)
        for path in directory.glob("*")
        if path.name not in expected
    )
    for path in orphans:
        if args.check:
            print(f"  ORPHAN: {shown(path)} — no figure declares it")
            stale.append(path.name)
        else:
            path.unlink()
            print(f"  removed {shown(path)} (no figure declares it)")

    if stale:
        if args.check:
            print(
                f"\nrender-figures: FAILED — {len(stale)} file(s) out of date. "
                "Run scripts/render-figures.py."
            )
        return 1

    note = f", {pending} awaiting a measurement" if pending else ""
    print(f"\nrender-figures: OK ({len(FIGURES)} figure(s){note})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
